# RabbitMQ properties
spring:
  rabbitmq:
    addresses:
    username:
    password:
    virtual_host:
    useSSL: false
    #  sslProperties:
    #  ssl:
    #    keyStore:
    #    keyStorePassphrase:
    #    trustStore:
    #    trustStorePassphrase:
#    channelCacheSize: 100