# RabbitMQ properties
spring:
  rabbitmq:
    addresses: localhost:5672
    adminAddresses: localhost:15672
    #  nodes: rabbit@localhost
    username: guest
    password: guest
    virtual_host: /
    useSSL: false
    #  sslProperties:
    #  ssl:
    #    keyStore:
    #    keyStorePassphrase:
    #    trustStore:
    #    trustStorePassphrase:
#    channelCacheSize: 100